version: '3'
services:
  codd_test_task:
    build:
      context: .
      dockerfile: .ci/Dockerfile
    container_name: codd_test_task
    image: sha256:96dd6a18e64e1ca08675a3df173ecfce283b4d84ef3d433ca5916e185ce91f22
    restart: always
    ports:
      - "8002:8002"
    environment:
    - PG_USER=postgres
    - PG_PASSWORD=pass
    - PG_DATABASE=codd_test_db
    - PG_HOST=postgres
    - PG_PORT=5432
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "codd_test_db"
      PG_HOST: "postgres"
      PG_PORT: "5432"
